# Run from the repository root.

# -----------------------------------------------------------------------------
# Parallel vintage sweep
# -----------------------------------------------------------------------------
# 1_backcast_fcast.R fits one date at a time, which is fine for a wiring check
# and hopeless for a sweep: a fit takes about 49 minutes, so a full weekly sweep
# over 2005-2021 is 816 fits, roughly 28 days serial. This distributes the dates
# across workers.
#
# Parallelising over DATES, not within a fit. fcast_dfm()'s `ncores` only
# parallelises the post-hoc rotation, which is a minority of the runtime; the
# Gibbs sampler is inherently serial. Dates are independent, so they are the
# right axis.
#
# Default here is 2019-2020: 96 weekly evaluation dates, about 26 hours on 3
# workers.
#
# Run this ONCE, not as two concurrent jobs. Eight simultaneous fits exhausted a
# 28 GB machine - each holds large sparse matrices, so the binding constraint is
# memory, not cores, and 16 cores is misleading. Three workers is the tested
# setting.
#
# Do NOT edit this file while a sweep is running. The workers re-source it, and
# a mid-run edit made every one of 48 fits fail with a parse error.
#
# 2019 is in the range for a reason. Every target quarter a 2020-only sweep
# reaches (2020Q1 to 2021Q1) is inside the Covid window of
# is_crisis_period_fcast(), so on its own it produces NO non-crisis rows: the
# crisis-vs-normal figures lose a panel and the Diebold-Mariano tests have
# nothing to compare crisis performance against. 2019 supplies the other side.
# -----------------------------------------------------------------------------

source("analysis/fcast/_setup.R")
library(foreach)
library(doParallel)

years <- 2019:2020
q_x <- 2
n_workers <- 3
run_benchmark <- TRUE
fit_root <- file.path("fits", "fcast_sweep")
mcmc <- list(length_sample = 1000, burn_in = 1000)

date_vec <- round(sort(unlist(lapply(years, function(y) seq(y, y + 47/48, 1/48)))), 3)


# DATA ------------------------------------------------------------------------
# The paper's own dataset, so the sweep is comparable with its stored panel.

e <- new.env(); load("analysis/fcast/reference/rda/data_ch.Rda", envir = e)
dat <- e$dat
stopifnot(target %in% names(dat$flows))

message(length(date_vec), " evaluation dates (", min(date_vec), " to ",
        max(date_vec), "), q = ", q_x, ", ", n_workers, " workers")
message("estimated wall-clock: ",
        round(length(date_vec) * 49.2 / 60 / n_workers, 1), " h")


# SWEEP -----------------------------------------------------------------------

dir.create(fit_root, recursive = TRUE, showWarnings = FALSE)
cl <- makeCluster(n_workers)
registerDoParallel(cl)
on.exit({ stopCluster(cl); message("cluster stopped") }, add = TRUE)

t0 <- Sys.time()

res <- foreach(ix = date_vec, .packages = c("mfbdfm", "Matrix", "zoo"),
               .errorhandling = "pass") %dopar% {

  # Skip work already on disk, so an interrupted sweep resumes instead of
  # starting over - 10 hours is long enough that this matters.
  f <- file.path(fit_root, paste0("q", q_x), paste0("fit_", round(ix, 3), ".Rda"))
  if (file.exists(f)) return(paste("skip", ix))

  rt <- cut_data(dat, ix)
  if (!target %in% names(rt$flows)) return(paste("no target at", ix))

  run_fcast(flows = rt$flows, stocks = rt$stocks, target = target,
            date = ix, dataset_used = paste0("q", q_x), q = q_x,
            length_sample = mcmc$length_sample, burn_in = mcmc$burn_in,
            output_dir = fit_root)

  if (run_benchmark) {
    source("analysis/fcast/_setup.R", local = TRUE)
    source_bmdfm_functions()
    source("analysis/fcast/bmdfm_benchmark.R", local = TRUE)
    mon <- week2mon(rt)
    try(run_bmdfm(flows = mon$flows, stocks = mon$stocks, target = target,
                  date = ix, dataset_used = paste0("bmdfm_q", q_x),
                  n_f = q_x, output_dir = fit_root), silent = TRUE)
  }

  paste("done", ix)
}

el <- round(as.numeric(difftime(Sys.time(), t0, units = "hours")), 2)
errs <- vapply(res, function(x) inherits(x, "error"), logical(1))
message("\nsweep finished in ", el, " h; ", sum(!errs), " ok, ", sum(errs), " failed")

# Failures go to a FILE, not just a message(). A sweep runs for hours,
# unattended, and its console output is usually piped through a filter - the
# first run of this script lost the only diagnostic from 48 failed fits that
# way. The log survives regardless of what the caller does with stdout.
log_path <- file.path(fit_root, "sweep_failures.log")
if (any(errs)) {
  msgs <- vapply(res[errs], conditionMessage, character(1))
  writeLines(c(paste("sweep at", format(Sys.time())),
               paste(sum(errs), "of", length(res), "dates failed"),
               "", paste0(date_vec[errs], ": ", msgs)), log_path)
  message("failures written to ", log_path)
  message("most common: ", names(sort(table(msgs), decreasing = TRUE))[1])
} else if (file.exists(log_path)) {
  unlink(log_path)
}
message("fits under ", fit_root, ": ",
        length(list.files(fit_root, recursive = TRUE)))
